[project]
name = "src"
version = "0.1.0"
description = ""
authors = [
    {name = "fddiferd",email = "fddiferd@gmail.com"}
]
packages = [{include = "src"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.103.1",
    "uvicorn>=0.23.2",
    "firebase-admin>=6.2.0",
    "google-cloud-firestore>=2.11.1",
    "pydantic>=2.3.0"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
