steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/wedge-golf-dev/wedge-api:$COMMIT_SHA', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/wedge-golf-dev/wedge-api:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wedge-api'
      - '--image'
      - 'gcr.io/wedge-golf-dev/wedge-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--project'
      - 'wedge-golf-dev'
      - '--set-env-vars'
      - 'ENVIRONMENT=dev,FIREBASE_CRED_PATH=service_accounts/firebase-dev.json'
  
# Tag the image for easier reference
images:
  - 'gcr.io/wedge-golf-dev/wedge-api:$COMMIT_SHA'

# Set timeout to 20 minutes
timeout: 1200s 