steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/wedge-api:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wedge-api:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wedge-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/wedge-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '512Mi'
      - '--set-env-vars'
      - 'ENVIRONMENT=${_ENVIRONMENT},FIREBASE_CRED_PATH=service_accounts/firebase-${_ENVIRONMENT}.json'
  
# Tag the image for easier reference
images:
  - 'gcr.io/$PROJECT_ID/wedge-api:$COMMIT_SHA'

# Set timeout to 20 minutes
timeout: 1200s 